/* frontend-utils.c generated by valac 0.10.4, the Vala compiler
 * generated from frontend-utils.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <libnotify/notify.h>
#include <stdio.h>
#include <gdk/gdk.h>
#include <gobject/gvaluecollector.h>


#define ICP_TYPE_FRONTEND (icp_frontend_get_type ())
#define ICP_FRONTEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ICP_TYPE_FRONTEND, icpFrontend))
#define ICP_FRONTEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ICP_TYPE_FRONTEND, icpFrontendClass))
#define ICP_IS_FRONTEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ICP_TYPE_FRONTEND))
#define ICP_IS_FRONTEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ICP_TYPE_FRONTEND))
#define ICP_FRONTEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ICP_TYPE_FRONTEND, icpFrontendClass))

typedef struct _icpFrontend icpFrontend;
typedef struct _icpFrontendClass icpFrontendClass;
typedef struct _icpFrontendPrivate icpFrontendPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _icpParamSpecFrontend icpParamSpecFrontend;

struct _icpFrontend {
	GTypeInstance parent_instance;
	volatile int ref_count;
	icpFrontendPrivate * priv;
};

struct _icpFrontendClass {
	GTypeClass parent_class;
	void (*finalize) (icpFrontend *self);
};

struct _icpParamSpecFrontend {
	GParamSpec parent_instance;
};


static char* icp_frontend__selection;
static GStaticRecMutex __lock_icp_frontend__selection = {0};
static char* icp_frontend__selection = NULL;
static GtkClipboard* icp_frontend_clipboard;
static GtkClipboard* icp_frontend_clipboard = NULL;
static guint64 icp_frontend__clipboard_update_time;
static guint64 icp_frontend__clipboard_update_time = 0ULL;
static gpointer icp_frontend_parent_class = NULL;

gpointer icp_frontend_ref (gpointer instance);
void icp_frontend_unref (gpointer instance);
GParamSpec* icp_param_spec_frontend (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void icp_value_set_frontend (GValue* value, gpointer v_object);
void icp_value_take_frontend (GValue* value, gpointer v_object);
gpointer icp_value_get_frontend (const GValue* value);
GType icp_frontend_get_type (void) G_GNUC_CONST;
enum  {
	ICP_FRONTEND_DUMMY_PROPERTY
};
static icpFrontend* icp_frontend_new (void);
static icpFrontend* icp_frontend_construct (GType object_type);
char* icp_frontend_get_selection (void);
void icp_frontend_notify (const char* title, const char* content, const char* icon);
guint64 icp_frontend_get_current_time (void);
void icp_frontend_clear_selection (void);
void icp_frontend_init (void);
static void _lambda1_ (void);
static void icp_frontend_set_clipboard_update_time (guint64 value);
static void __lambda1__gtk_clipboard_owner_change (GtkClipboard* _sender, GdkEvent* p0, gpointer self);
guint64 icp_frontend_get_clipboard_update_time (void);
static void icp_frontend_finalize (icpFrontend* obj);



static icpFrontend* icp_frontend_construct (GType object_type) {
	icpFrontend* self = (icpFrontend*) g_type_create_instance (object_type);
	return self;
}


static icpFrontend* icp_frontend_new (void) {
	return icp_frontend_construct (ICP_TYPE_FRONTEND);
}


char* icp_frontend_get_selection (void) {
	char* result = NULL;
	result = g_strdup (icp_frontend__selection);
	return result;
}


void icp_frontend_notify (const char* title, const char* content, const char* icon) {
	NotifyNotification* notification;
	GError * _inner_error_ = NULL;
	g_return_if_fail (title != NULL);
	notification = notify_notification_new (title, content, icon, NULL);
	{
		notify_notification_show (notification, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch7_g_error;
		}
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stdout, "Notification: %s %s %s\n", title, content, icon);
			;
			_g_error_free0 (e);
		}
	}
	__finally7:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (notification);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (notification);
}


guint64 icp_frontend_get_current_time (void) {
	guint64 result = 0ULL;
	GTimeVal tv = {0};
	g_get_current_time (&tv);
	g_get_current_time (&tv);
	result = tv.tv_usec + (((guint64) tv.tv_sec) * 1000000);
	return result;
}


void icp_frontend_clear_selection (void) {
	char* _tmp0_;
	icp_frontend__selection = (_tmp0_ = g_strdup (""), _g_free0 (icp_frontend__selection), _tmp0_);
}


static void _lambda1_ (void) {
	GError * _inner_error_ = NULL;
	{
		g_static_rec_mutex_lock (&__lock_icp_frontend__selection);
		{
			char* _tmp0_;
			icp_frontend__selection = (_tmp0_ = g_strdup (gtk_clipboard_wait_for_text (icp_frontend_clipboard)), _g_free0 (icp_frontend__selection), _tmp0_);
			icp_frontend_set_clipboard_update_time (icp_frontend_get_current_time ());
		}
		__finally8:
		{
			g_static_rec_mutex_unlock (&__lock_icp_frontend__selection);
		}
		if (_inner_error_ != NULL) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
}


static void __lambda1__gtk_clipboard_owner_change (GtkClipboard* _sender, GdkEvent* p0, gpointer self) {
	_lambda1_ ();
}


void icp_frontend_init (void) {
	char* _tmp0_;
	if (notify_is_initted ()) {
		return;
	}
	icp_frontend__selection = (_tmp0_ = g_strdup (""), _g_free0 (icp_frontend__selection), _tmp0_);
	notify_init ("ibus-cloud-pinyin");
	icp_frontend_clipboard = gtk_clipboard_get_for_display (gdk_display_get_default (), GDK_SELECTION_PRIMARY);
	g_signal_connect (icp_frontend_clipboard, "owner-change", (GCallback) __lambda1__gtk_clipboard_owner_change, NULL);
}


guint64 icp_frontend_get_clipboard_update_time (void) {
	guint64 result;
	result = icp_frontend__clipboard_update_time;
	return result;
}


static void icp_frontend_set_clipboard_update_time (guint64 value) {
	icp_frontend__clipboard_update_time = value;
}


static void icp_value_frontend_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void icp_value_frontend_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		icp_frontend_unref (value->data[0].v_pointer);
	}
}


static void icp_value_frontend_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = icp_frontend_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer icp_value_frontend_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* icp_value_frontend_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		icpFrontend* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = icp_frontend_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* icp_value_frontend_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	icpFrontend** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = icp_frontend_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* icp_param_spec_frontend (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	icpParamSpecFrontend* spec;
	g_return_val_if_fail (g_type_is_a (object_type, ICP_TYPE_FRONTEND), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer icp_value_get_frontend (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, ICP_TYPE_FRONTEND), NULL);
	return value->data[0].v_pointer;
}


void icp_value_set_frontend (GValue* value, gpointer v_object) {
	icpFrontend* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, ICP_TYPE_FRONTEND));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, ICP_TYPE_FRONTEND));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		icp_frontend_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		icp_frontend_unref (old);
	}
}


void icp_value_take_frontend (GValue* value, gpointer v_object) {
	icpFrontend* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, ICP_TYPE_FRONTEND));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, ICP_TYPE_FRONTEND));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		icp_frontend_unref (old);
	}
}


static void icp_frontend_class_init (icpFrontendClass * klass) {
	icp_frontend_parent_class = g_type_class_peek_parent (klass);
	ICP_FRONTEND_CLASS (klass)->finalize = icp_frontend_finalize;
	g_static_rec_mutex_init (&__lock_icp_frontend__selection);
}


static void icp_frontend_instance_init (icpFrontend * self) {
	self->ref_count = 1;
}


static void icp_frontend_finalize (icpFrontend* obj) {
	icpFrontend * self;
	self = ICP_FRONTEND (obj);
}


GType icp_frontend_get_type (void) {
	static volatile gsize icp_frontend_type_id__volatile = 0;
	if (g_once_init_enter (&icp_frontend_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { icp_value_frontend_init, icp_value_frontend_free_value, icp_value_frontend_copy_value, icp_value_frontend_peek_pointer, "p", icp_value_frontend_collect_value, "p", icp_value_frontend_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (icpFrontendClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) icp_frontend_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (icpFrontend), 0, (GInstanceInitFunc) icp_frontend_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType icp_frontend_type_id;
		icp_frontend_type_id = g_type_register_fundamental (g_type_fundamental_next (), "icpFrontend", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&icp_frontend_type_id__volatile, icp_frontend_type_id);
	}
	return icp_frontend_type_id__volatile;
}


gpointer icp_frontend_ref (gpointer instance) {
	icpFrontend* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void icp_frontend_unref (gpointer instance) {
	icpFrontend* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		ICP_FRONTEND_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}




